### ISSUE TITLE
Update version on PyPi

### ISSUE THREAD

**Issue by Mause** [epmoyer/ipy_table#11]
But please make sure to bump the version first :)

**Comment by kevcampb** [comment]
Adding a me too on this. We use ipy_table quite a bit, it's simple and does the job nicely. Breaking on unicode is an issue though, and it would be much nicer to use the pypi package rather than git links.

**Comment by epmoyer** [comment]
![faceplant](https://user-images.githubusercontent.com/136718/29678163-628a0058-88b2-11e7-99ac-e71fd786a216.jpg)
Sorry that the PyPi update took me so *very* long.  Thanks for reminding me again @kevcampb.  And apologies in general for being absent on this project for so long.

- I had to update the email syntax in setup.py to get PyPi to accept the submission, hence the bump to `1.14`
- Per @Mause  I dropped the "v" from the tag, so the new file on PyPi is `ipy_table-1.14.tar.gz` (rather than `ipy_table-v1.14.tar.gz`), and pip will upgrade from `1.12` to `1.14` properly.
- I have other changes I'd like to make, and PRs to service, but I thought the first order of business should be to get the current release onto PyPi, so `1.14` contains no changes other than what was necessary to get PyPi updated.

Thanks for your feedback everyone, and apologies again for the delay.

Cheers!
